<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookCatalog [
  <!ELEMENT bookCatalog (book+)>
  <!ELEMENT book (title, author, genre, price, availability)>
  <!ATTLIST book id ID #REQUIRED>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT genre (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ATTLIST price currency CDATA #REQUIRED>
  <!ELEMENT availability (#PCDATA)>
]>
<bookCatalog>

  <book id="B001">
    <title>The Alchemist</title>
    <author>Paulo Coelho</author>
    <genre>Fiction</genre>
    <price currency="INR">299</price>
    <availability>In Stock</availability>
  </book>

  <book id="B002">
    <title>Atomic Habits</title>
    <author>James Clear</author>
    <genre>Self Help</genre>
    <price currency="INR">399</price>
    <availability>In Stock</availability>
  </book>

  <book id="B003">
    <title>Sapiens</title>
    <author>Yuval Noah Harari</author>
    <genre>History</genre>
    <price currency="INR">499</price>
    <availability>In Stock</availability>
  </book>

</bookCatalog>
